plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version "0.7.+"
}

group = mod_group_id
version = mod_version

base {
    archivesName = 'solaris_rpg'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                'solaris_rpg' {
                    source sourceSets.main
                }
            }
        }
        client {
            property 'forge.enabledGameTestNamespaces', 'solaris_rpg'
            jvmArgs("-Xmx6G")
        }
        server {
            property 'forge.enabledGameTestNamespaces', 'solaris_rpg'
            args '--nogui'
        }
    }
}

mixin {
    add sourceSets.main, "solaris_rpg.refmap.json"
}

repositories {
    flatDir { dir rootProject.file('libs') }
    maven {
        url = "https://maven.architectury.dev"
        content { includeGroup "dev.architectury" }
    }
    maven { url 'https://modmaven.dev/' }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("libs:ldlib-forge-1.20.1:1.0.52.a")
    implementation fg.deobf("dev.architectury:architectury-forge:${architectury_version}")

    compileOnly fg.deobf("libs:kubejs-forge:${kubejs_version}")
    compileOnly fg.deobf("libs:rhino-forge:${rhino_version}")
    runtimeOnly fg.deobf("libs:kubejs-forge:${kubejs_version}")
    runtimeOnly fg.deobf("libs:rhino-forge:${rhino_version}")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_license         : mod_license, mod_version: mod_version, mod_authors: mod_authors]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : 'solaris_rpg',
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
