#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 03 20:11:06 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=BSL_v10.1.5 + Clrwl_1.0.5.zip
enableShaders=false
